version: "3.9"

services:

  # PostgreSQL database
  collect-db:
    image: postgis/postgis:12-3.4
    container_name: collect-db
    platform: linux/amd64
    environment:
      POSTGRES_DB: collect
      POSTGRES_USER: collect
      POSTGRES_PASSWORD: collect123
    ports:
      - "5433:5432"  # host port 5433 -> container port 5432
    networks:
      - collect-network
    restart: unless-stopped

  # OpenForis Collect web application
  collect-app:
    platform: linux/amd64   # ← move platform here (service level)
    build:
      context: ./collect-master   # path to your Dockerfile
      dockerfile: Dockerfile
    container_name: collect-app
    env_file:
      - ./collect.env
    ports:
      - "8080:8080"  # access via http://localhost:8080/collect
    networks:
      - collect-network
    depends_on:
      - collect-db
    restart: unless-stopped

networks:
  collect-network:
    driver: bridge
